#### RandomForest
- 집단 학습을 기반으로 고정밀 분류, 회귀, 클러스터링 등을 구현
- 학습 전용 데이터를 기반으로 다수의 의사결정트리를 만들고 만들어진 의사결정 트리를 기반으로 다수결로 결과를 유도하는 모델

In [110]:
import pandas as pd

In [111]:
iris = pd.read_csv("../Data/iris.csv")
iris

     SepalLength  SepalWidth  PetalLength  PetalWidth            Name
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [112]:
# Feature와 Target 분리
iris_data = iris[['SepalLength', 'SepalWidth','PetalLength','PetalWidth']]
iris_target = iris['Name']

In [113]:
print(iris_data.shape)
print(iris_target.shape)

(150, 4)
(150,)

#### Train과 Test 분리

In [114]:
from sklearn.model_selection import train_test_split

In [115]:
train_data, test_data, train_target, test_target =\
train_test_split(
   iris_data,
   iris_target,
   random_state=42,
   stratify=iris_target
)

In [116]:
print(train_data.shape)
print(test_data.shape)
print(train_target.shape)
print(test_target.shape)

(112, 4)
(38, 4)
(112,)
(38,)

#### RandomForest 분류

In [117]:
from sklearn.ensemble import RandomForestClassifier

In [118]:
# 모델 만들기
clf = RandomForestClassifier()

In [119]:
# 학습 시키기
clf.fit(train_data, train_target)

RandomForestClassifier()

In [120]:
# 평가하기
clf.score(test_data, test_target)

0.9210526315789473

----
#### 독버섯과 관련된 데이터를 사용한 머신러닝
- 8124종류의 버섯의 특징과 독의 유무로 구성되어 있는 데이터셋
- 버섯의 특징을 기반으로 독의 유무를 판단

In [121]:
# 데이터 획득하기
import urllib.request as req 

local = "../Data/mushroom.csv"
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/mushroom/agaricus-lepiota.data"
req.urlretrieve(url, local)
print('OK')

OK

#### 랜덤포레스틀 이용한 버섯 분류

In [122]:
import pandas as pd

In [123]:
mr = pd.read_csv("../Data/mushroom.csv", header=None)
mr.head()

  0  1  2  3  4  5  6  7  8  9   ... 13 14 15 16 17 18 19 20 21 22
0  p  x  s  n  t  p  f  c  n  k  ...  s  w  w  p  w  o  p  k  s  u
1  e  x  s  y  t  a  f  c  b  k  ...  s  w  w  p  w  o  p  n  n  g
2  e  b  s  w  t  l  f  c  b  n  ...  s  w  w  p  w  o  p  n  n  m
3  p  x  y  w  t  p  f  c  n  n  ...  s  w  w  p  w  o  p  k  s  u
4  e  x  s  g  f  n  f  w  b  k  ...  s  w  w  p  w  o  e  n  a  g

[5 rows x 23 columns]

In [124]:
mr.shape

(8124, 23)

- 한 줄이 버섯 한 종류
- 첫번째 열 : p(독버섯), e(식용)
- 두번째 열 : 버섯의 머리 모양 -> b(벨형태), c(원뿔), x(볼록), f(평평), k(혹), s(오목)
- 네번째 열 : 버섯의 머리 색깔 -> n(갈색), b(황갈색), c(연한갈색)

#### Feature Data가 알파벳 1자리 문자 -> 숫자로 변환

----
#### 연습

In [125]:
# 알파벳 -> ASCII
ord('x')

120

In [126]:
# ASCII -> 알파벳
chr(120)

'x'

In [127]:
# mr의 1번 컬럼을 숫자로 변경
for i in mr.loc[:,1]:
   print(i, ord(i))

x 120
x 120
b 98
x 120
x 120
x 120
b 98
b 98
x 120
b 98
x 120
x 120
b 98
x 120
x 120
s 115
f 102
x 120
x 120
x 120
b 98
x 120
b 98
b 98
b 98
f 102
x 120
x 120
f 102
x 120
b 98
x 120
x 120
x 120
b 98
x 120
s 115
x 120
x 120
b 98
b 98
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
b 98
x 120
x 120
b 98
f 102
b 98
x 120
x 120
s 115
b 98
b 98
b 98
b 98
f 102
x 120
f 102
x 120
x 120
f 102
b 98
f 102
x 120
b 98
f 102
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
b 98
x 120
f 102
s 115
x 120
b 98
x 120
x 120
x 120
x 120
f 102
x 120
b 98
x 120
x 120
b 98
f 102
x 120
b 98
x 120
x 120
b 98
b 98
x 120
x 120
s 115
x 120
x 120
x 120
x 120
s 115
x 120
x 120
s 115
x 120
x 120
f 102
f 102
x 120
x 120
b 98
f 102
x 120
b 98
b 98
b 98
f 102
x 120
f 102
x 120
f 102
x 120
x 120
b 98
x 120
b 98
s 115
f 102
x 120
x 120
f 102
x 120
b 98
b 98
x 120
x 120
x 120
s 115
x 120
x 120
b 98
x 120
b 98
b 98
b 98
b 98
x 120
f 102
x 120
f 102
b 98
b 98
x 120
b 98
x 120
b 98
x 120
b 98
f 102
b 98
b 98
b 98
x 120
b 98
x 120
s 115
f 102
x 120
f 102
x 120
b 98
f 102
b 98
x 120
x 120
x 120
b 98
f 102
x 120
f 102
b 98
x 120
x 120
f 102
x 120
b 98
x 120
x 120
f 102
x 120
b 98
b 98
b 98
b 98
x 120
b 98
x 120
x 120
f 102
b 98
x 120
x 120
x 120
s 115
x 120
x 120
x 120
f 102
x 120
b 98
x 120
x 120
x 120
b 98
x 120
x 120
x 120
f 102
b 98
x 120
x 120
b 98
x 120
f 102
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
s 115
b 98
b 98
b 98
f 102
x 120
b 98
b 98
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
b 98
f 102
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
b 98
s 115
x 120
b 98
f 102
b 98
b 98
x 120
f 102
x 120
b 98
x 120
b 98
x 120
b 98
x 120
x 120
f 102
x 120
x 120
b 98
x 120
b 98
x 120
x 120
b 98
x 120
f 102
x 120
x 120
x 120
x 120
x 120
b 98
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
b 98
x 120
b 98
x 120
x 120
b 98
b 98
x 120
b 98
b 98
b 98
x 120
x 120
x 120
b 98
x 120
x 120
x 120
b 98
x 120
f 102
b 98
x 120
x 120
x 120
f 102
x 120
f 102
f 102
b 98
b 98
x 120
s 115
f 102
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
b 98
x 120
x 120
f 102
x 120
s 115
x 120
b 98
s 115
b 98
x 120
b 98
x 120
x 120
x 120
b 98
x 120
x 120
x 120
x 120
b 98
x 120
b 98
x 120
b 98
x 120
f 102
x 120
x 120
x 120
x 120
x 120
b 98
b 98
x 120
b 98
x 120
x 120
b 98
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
b 98
x 120
x 120
x 120
f 102
x 120
b 98
x 120
f 102
x 120
x 120
f 102
b 98
x 120
f 102
x 120
x 120
b 98
b 98
f 102
b 98
x 120
x 120
b 98
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
b 98
x 120
x 120
b 98
b 98
x 120
b 98
x 120
b 98
b 98
f 102
f 102
x 120
f 102
b 98
x 120
x 120
f 102
x 120
x 120
b 98
f 102
x 120
x 120
f 102
s 115
f 102
f 102
x 120
b 98
x 120
b 98
b 98
b 98
f 102
f 102
f 102
f 102
x 120
s 115
x 120
x 120
f 102
f 102
x 120
f 102
x 120
b 98
f 102
f 102
x 120
b 98
x 120
b 98
x 120
b 98
b 98
x 120
x 120
f 102
x 120
f 102
f 102
b 98
x 120
s 115
x 120
x 120
x 120
b 98
x 120
x 120
x 120
b 98
f 102
x 120
f 102
b 98
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
b 98
s 115
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
b 98
f 102
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
b 98
x 120
x 120
x 120
b 98
x 120
x 120
f 102
x 120
b 98
x 120
f 102
x 120
b 98
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
s 115
f 102
s 115
x 120
x 120
x 120
x 120
x 120
x 120
x 120
b 98
b 98
x 120
x 120
x 120
x 120
f 102
f 102
b 98
b 98
x 120
f 102
x 120
f 102
f 102
x 120
f 102
x 120
x 120
b 98
f 102
b 98
b 98
s 115
f 102
b 98
x 120
f 102
f 102
x 120
f 102
s 115
b 98
b 98
f 102
b 98
x 120
x 120
x 120
b 98
f 102
x 120
x 120
x 120
b 98
x 120
f 102
f 102
f 102
x 120
b 98
b 98
x 120
f 102
x 120
b 98
f 102
x 120
x 120
x 120
f 102
b 98
x 120
f 102
b 98
x 120
x 120
x 120
b 98
b 98
f 102
x 120
f 102
x 120
x 120
f 102
f 102
x 120
f 102
f 102
f 102
x 120
x 120
b 98
x 120
x 120
x 120
b 98
x 120
x 120
f 102
b 98
x 120
x 120
b 98
b 98
x 120
f 102
x 120
b 98
b 98
x 120
x 120
f 102
x 120
f 102
x 120
b 98
f 102
f 102
b 98
s 115
x 120
b 98
f 102
f 102
x 120
b 98
b 98
b 98
b 98
x 120
x 120
s 115
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
b 98
x 120
f 102
x 120
x 120
x 120
x 120
b 98
x 120
x 120
x 120
x 120
x 120
b 98
x 120
b 98
f 102
x 120
b 98
b 98
x 120
f 102
x 120
b 98
f 102
b 98
b 98
b 98
f 102
x 120
b 98
x 120
b 98
f 102
x 120
x 120
x 120
f 102
x 120
f 102
b 98
b 98
x 120
b 98
x 120
x 120
f 102
x 120
x 120
x 120
x 120
b 98
x 120
s 115
b 98
x 120
x 120
x 120
x 120
x 120
x 120
x 120
b 98
f 102
x 120
x 120
x 120
x 120
b 98
x 120
x 120
x 120
b 98
x 120
x 120
b 98
b 98
f 102
b 98
x 120
b 98
x 120
b 98
b 98
x 120
x 120
x 120
x 120
x 120
x 120
x 120
b 98
b 98
x 120
b 98
x 120
x 120
x 120
f 102
f 102
x 120
f 102
s 115
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
b 98
s 115
x 120
x 120
x 120
b 98
b 98
x 120
b 98
f 102
s 115
x 120
s 115
f 102
f 102
b 98
b 98
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
b 98
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
b 98
x 120
x 120
b 98
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
b 98
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
b 98
x 120
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
x 120
b 98
x 120
x 120
x 120
f 102
f 102
f 102
b 98
f 102
f 102
x 120
b 98
f 102
x 120
f 102
b 98
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
b 98
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
b 98
f 102
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
f 102
f 102
f 102
x 120
f 102
x 120
f 102
b 98
b 98
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
b 98
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
b 98
f 102
b 98
f 102
b 98
x 120
f 102
x 120
s 115
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
f 102
b 98
x 120
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
b 98
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
b 98
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
b 98
x 120
f 102
f 102
f 102
b 98
x 120
x 120
x 120
x 120
b 98
x 120
x 120
f 102
b 98
x 120
x 120
f 102
x 120
x 120
x 120
b 98
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
b 98
x 120
x 120
b 98
x 120
b 98
x 120
x 120
b 98
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
f 102
f 102
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
f 102
x 120
f 102
f 102
x 120
x 120
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
f 102
b 98
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
b 98
f 102
f 102
x 120
b 98
x 120
f 102
x 120
f 102
f 102
x 120
f 102
b 98
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
x 120
f 102
x 120
f 102
f 102
x 120
x 120
b 98
x 120
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
b 98
f 102
f 102
x 120
x 120
x 120
f 102
f 102
f 102
f 102
x 120
f 102
x 120
f 102
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
f 102
b 98
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
f 102
f 102
b 98
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
b 98
f 102
f 102
f 102
f 102
x 120
b 98
f 102
f 102
x 120
f 102
x 120
x 120
b 98
x 120
f 102
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
f 102
x 120
b 98
x 120
x 120
f 102
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
f 102
x 120
x 120
b 98
f 102
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
f 102
b 98
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
b 98
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
b 98
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
x 120
x 120
b 98
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
x 120
f 102
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
f 102
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
x 120
f 102
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
f 102
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
x 120
f 102
x 120
f 102
f 102
f 102
x 120
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
f 102
f 102
x 120
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
f 102

----

In [128]:
target = []
data = []

for row_index, row in mr.iterrows():
   #print(row_index, ":", row)
   #print(row.loc[0])
   #print(row.loc[1])
   target.append(row.loc[0])
   row_data = []
   for v in row.loc[1:]:
      row_data.append(ord(v))
   data.append(row_data)

print(data[:2])

[[120, 115, 110, 116, 112, 102, 99, 110, 107, 101, 101, 115, 115, 119, 119, 112, 119, 111, 112, 107, 115, 117], [120, 115, 121, 116, 97, 102, 99, 98, 107, 101, 99, 115, 115, 119, 119, 112, 119, 111, 112, 110, 110, 103]]

In [129]:
print(target[:2])

['p', 'e']

#### DataFrame 만들기

In [130]:
# Target을 기준으로 DataFrame만들기

targetTemp = pd.DataFrame(target)
targetTemp.head()

   0
0  p
1  e
2  e
3  p
4  e

In [131]:
# data를 dataframe으로 만들고 column 이름을 겹치지 않게 하기
dataTemp = pd.DataFrame(data)
dataTemp.rename(columns=lambda x: x+1, inplace=True)
dataTemp.head()

,1,2,3,4,5,6,7,8,9,10,...,13,14,15,16,17,18,19,20,21,22
0,120,115,110,116,112,102,99,110,107,101,...,115,119,119,112,119,111,112,107,115,117
1,120,115,121,116,97,102,99,98,107,101,...,115,119,119,112,119,111,112,110,110,103
2,98,115,119,116,108,102,99,98,110,101,...,115,119,119,112,119,111,112,110,110,109
3,120,121,119,116,112,102,99,110,110,101,...,115,119,119,112,119,111,112,107,115,117
4,120,115,103,102,110,102,119,98,107,116,...,115,119,119,112,119,111,101,110,97,103

In [132]:
# 2개의 dataframe 합치기
mr2 = pd.concat([targetTemp, dataTemp], axis='columns')
mr2.head()

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,p,120,115,110,116,112,102,99,110,107,...,115,119,119,112,119,111,112,107,115,117
1,e,120,115,121,116,97,102,99,98,107,...,115,119,119,112,119,111,112,110,110,103
2,e,98,115,119,116,108,102,99,98,110,...,115,119,119,112,119,111,112,110,110,109
3,p,120,121,119,116,112,102,99,110,110,...,115,119,119,112,119,111,112,107,115,117
4,e,120,115,103,102,110,102,119,98,107,...,115,119,119,112,119,111,101,110,97,103

In [133]:
mr2.isna

<bound method DataFrame.isna of      0    1    2    3    4    5    6    7    8    9   ...   13   14   15   16  \
0     p  120  115  110  116  112  102   99  110  107  ...  115  119  119  112
1     e  120  115  121  116   97  102   99   98  107  ...  115  119  119  112
2     e   98  115  119  116  108  102   99   98  110  ...  115  119  119  112
3     p  120  121  119  116  112  102   99  110  110  ...  115  119  119  112
4     e  120  115  103  102  110  102  119   98  107  ...  115  119  119  112
...  ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
8119  e  107  115  110  102  110   97   99   98  121  ...  115  111  111  112
8120  e  120  115  110  102  110   97   99   98  121  ...  115  111  111  112
8121  e  102  115  110  102  110   97   99   98  110  ...  115  111  111  112
8122  p  107  121  110  102  121  102   99  110   98  ...  107  119  119  112
8123  e  120  115  110  102  110   97   99   98  121  ...  115  111  111  112

       17   18   19   20   21   22
0     119  111  112  107  115  117
1     119  111  112  110  110  103
2     119  111  112  110  110  109
3     119  111  112  107  115  117
4     119  111  101  110   97  103
...   ...  ...  ...  ...  ...  ...
8119  111  111  112   98   99  108
8120  110  111  112   98  118  108
8121  111  111  112   98   99  108
8122  119  111  101  119  118  108
8123  111  111  112  111   99  108

[8124 rows x 23 columns]>

In [134]:
mr2.info

<bound method DataFrame.info of      0    1    2    3    4    5    6    7    8    9   ...   13   14   15   16  \
0     p  120  115  110  116  112  102   99  110  107  ...  115  119  119  112
1     e  120  115  121  116   97  102   99   98  107  ...  115  119  119  112
2     e   98  115  119  116  108  102   99   98  110  ...  115  119  119  112
3     p  120  121  119  116  112  102   99  110  110  ...  115  119  119  112
4     e  120  115  103  102  110  102  119   98  107  ...  115  119  119  112
...  ..  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
8119  e  107  115  110  102  110   97   99   98  121  ...  115  111  111  112
8120  e  120  115  110  102  110   97   99   98  121  ...  115  111  111  112
8121  e  102  115  110  102  110   97   99   98  110  ...  115  111  111  112
8122  p  107  121  110  102  121  102   99  110   98  ...  107  119  119  112
8123  e  120  115  110  102  110   97   99   98  121  ...  115  111  111  112

       17   18   19   20   21   22
0     119  111  112  107  115  117
1     119  111  112  110  110  103
2     119  111  112  110  110  109
3     119  111  112  107  115  117
4     119  111  101  110   97  103
...   ...  ...  ...  ...  ...  ...
8119  111  111  112   98   99  108
8120  110  111  112   98  118  108
8121  111  111  112   98   99  108
8122  119  111  101  119  118  108
8123  111  111  112  111   99  108

[8124 rows x 23 columns]>

### RandomFroest로 분류하기

In [135]:
from sklearn.model_selection import train_test_split

In [136]:
# Train과 Test 분리

train_data, test_data, train_target, test_target = \
train_test_split (
   mr2.loc[:,1:],
   mr2.loc[:,0],
   random_state=42,
   stratify=mr2.loc[:,0]
)

In [144]:
# 데이터를 학습하고 예측

clf = RandomForestClassifier()
clf.fit(train_data, train_target)

print("training:", clf.score(train_data, train_target))
print("test:", clf.score(test_data, test_target))

training: 1.0
test: 1.0

---
#### One-hot Encoding
- 숫자 데이터가 숫자로써 의미가 있우면 사관없지만 위의 데이터는 분류를 위한 데이터이므로 숫자 크기의 의미가 없다.
- 이때 사용하는 것이 One-hot Encoding

#### 연습

In [138]:
mr2.head()

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,p,120,115,110,116,112,102,99,110,107,...,115,119,119,112,119,111,112,107,115,117
1,e,120,115,121,116,97,102,99,98,107,...,115,119,119,112,119,111,112,110,110,103
2,e,98,115,119,116,108,102,99,98,110,...,115,119,119,112,119,111,112,110,110,109
3,p,120,121,119,116,112,102,99,110,110,...,115,119,119,112,119,111,112,107,115,117
4,e,120,115,103,102,110,102,119,98,107,...,115,119,119,112,119,111,101,110,97,103

In [139]:
mr2[1].unique()

array([120,  98, 115, 102, 107,  99])

In [140]:
pd.get_dummies(
   data=dataTemp,
   columns=[1],
   prefix='1'
)

,2,3,4,5,6,7,8,9,10,11,...,19,20,21,22,1_98,1_99,1_102,1_107,1_115,1_120
0,115,110,116,112,102,99,110,107,101,101,...,112,107,115,117,False,False,False,False,False,True
1,115,121,116,97,102,99,98,107,101,99,...,112,110,110,103,False,False,False,False,False,True
2,115,119,116,108,102,99,98,110,101,99,...,112,110,110,109,True,False,False,False,False,False
3,121,119,116,112,102,99,110,110,101,101,...,112,107,115,117,False,False,False,False,False,True
4,115,103,102,110,102,119,98,107,116,101,...,101,110,97,103,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8119,115,110,102,110,97,99,98,121,101,63,...,112,98,99,108,False,False,False,True,False,False
8120,115,110,102,110,97,99,98,121,101,63,...,112,98,118,108,False,False,False,False,False,True
8121,115,110,102,110,97,99,98,110,101,63,...,112,98,99,108,False,False,True,False,False,False
8122,121,110,102,121,102,99,110,98,116,63,...,101,119,118,108,False,False,False,True,False,False
8123,115,110,102,110,97,99,98,121,101,63,...,112,111,99,108,False,False,False,False,False,True

In [141]:
# 적용하기
for i in range(1,22+1):
   dataTemp = pd.get_dummies(
      data=dataTemp,
      columns=[i],
      prefix=[i]
   )

In [142]:
# dataframe 만들기
mr3 = pd.concat(
   [targetTemp, dataTemp],
   axis='columns'
)
mr3.head()

,0,1_98,1_99,1_102,1_107,1_115,1_120,2_102,2_103,2_115,...,21_115,21_118,21_121,22_100,22_103,22_108,22_109,22_112,22_117,22_119
0,p,False,False,False,False,False,True,False,False,True,...,True,False,False,False,False,False,False,False,True,False
1,e,False,False,False,False,False,True,False,False,True,...,False,False,False,False,True,False,False,False,False,False
2,e,True,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,True,False,False,False
3,p,False,False,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
4,e,False,False,False,False,False,True,False,False,True,...,False,False,False,False,True,False,False,False,False,False

In [143]:
mr3.shape

(8124, 118)

In [152]:
# Train과 Test 분리
train_data, test_data, train_target, test_target = \
train_test_split (
   mr3.iloc[:,1:],
   mr3.iloc[:,0],
   random_state=42,
   stratify=mr3.iloc[:,0]
)

In [153]:
clf = RandomForestClassifier()
clf.fit(train_data, train_target)

RandomForestClassifier()

In [155]:
print("training:", clf.score(train_data, train_target))
print("test:", clf.score(test_data, test_target))

training: 1.0
test: 1.0