#### RandomForest
- 집단 학습을 기반으로 고정밀 분류, 회귀, 클러스터링 등을 구현
- 학습 전용 데이터를 기반으로 다수의 의사결정트리를 만들고 만들어진 의사결정 트리를 기반으로 다수결로 결과를 유도하는 모델

In [26]:
import pandas as pd

In [27]:
iris = pd.read_csv("../Data/iris.csv")
iris

     SepalLength  SepalWidth  PetalLength  PetalWidth            Name
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [28]:
# Feature와 Target 분리
iris_data = iris[['SepalLength', 'SepalWidth','PetalLength','PetalWidth']]
iris_target = iris['Name']

In [29]:
print(iris_data.shape)
print(iris_target.shape)

(150, 4)
(150,)

#### Train과 Test 분리

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
train_data, test_data, train_target, test_target =\
train_test_split(
   iris_data,
   iris_target,
   random_state=42,
   stratify=iris_target
)

In [32]:
print(train_data.shape)
print(test_data.shape)
print(train_target.shape)
print(test_target.shape)

(112, 4)
(38, 4)
(112,)
(38,)

#### RandomForest 분류

In [33]:
from sklearn.ensemble import RandomForestClassifier

In [34]:
# 모델 만들기
clf = RandomForestClassifier()

In [35]:
# 학습 시키기
clf.fit(train_data, train_target)

RandomForestClassifier()

In [36]:
# 평가하기
clf.score(test_data, test_target)

0.9210526315789473

----
#### 독버섯과 관련된 데이터를 사용한 머신러닝
- 8124종류의 버섯의 특징과 독의 유무로 구성되어 있는 데이터셋
- 버섯의 특징을 기반으로 독의 유무를 판단

In [37]:
# 데이터 획득하기
import urllib.request as req 

local = "../Data/mushroom.csv"
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/mushroom/agaricus-lepiota.data"
req.urlretrieve(url, local)
print('OK')

OK

#### 랜덤포레스틀 이용한 버섯 분류

In [38]:
import pandas as pd

In [39]:
mr = pd.read_csv("../Data/mushroom.csv", header=None)
mr.head()

  0  1  2  3  4  5  6  7  8  9   ... 13 14 15 16 17 18 19 20 21 22
0  p  x  s  n  t  p  f  c  n  k  ...  s  w  w  p  w  o  p  k  s  u
1  e  x  s  y  t  a  f  c  b  k  ...  s  w  w  p  w  o  p  n  n  g
2  e  b  s  w  t  l  f  c  b  n  ...  s  w  w  p  w  o  p  n  n  m
3  p  x  y  w  t  p  f  c  n  n  ...  s  w  w  p  w  o  p  k  s  u
4  e  x  s  g  f  n  f  w  b  k  ...  s  w  w  p  w  o  e  n  a  g

[5 rows x 23 columns]

In [40]:
mr.shape

(8124, 23)

- 한 줄이 버섯 한 종류
- 첫번째 열 : p(독버섯), e(식용)
- 두번째 열 : 버섯의 머리 모양 -> b(벨형태), c(원뿔), x(볼록), f(평평), k(혹), s(오목)
- 네번째 열 : 버섯의 머리 색깔 -> n(갈색), b(황갈색), c(연한갈색)

#### Feature Data가 알파벳 1자리 문자 -> 숫자로 변환

----
#### 연습

In [41]:
# 알파벳 -> ASCII
ord('x')

120

In [42]:
# ASCII -> 알파벳
chr(120)

'x'

In [43]:
# mr의 1번 컬럼을 숫자로 변경
for i in mr.loc[:,1]:
   print(i, ord(i))

x 120
x 120
b 98
x 120
x 120
x 120
b 98
b 98
x 120
b 98
x 120
x 120
b 98
x 120
x 120
s 115
f 102
x 120
x 120
x 120
b 98
x 120
b 98
b 98
b 98
f 102
x 120
x 120
f 102
x 120
b 98
x 120
x 120
x 120
b 98
x 120
s 115
x 120
x 120
b 98
b 98
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
b 98
x 120
x 120
b 98
f 102
b 98
x 120
x 120
s 115
b 98
b 98
b 98
b 98
f 102
x 120
f 102
x 120
x 120
f 102
b 98
f 102
x 120
b 98
f 102
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
b 98
x 120
f 102
s 115
x 120
b 98
x 120
x 120
x 120
x 120
f 102
x 120
b 98
x 120
x 120
b 98
f 102
x 120
b 98
x 120
x 120
b 98
b 98
x 120
x 120
s 115
x 120
x 120
x 120
x 120
s 115
x 120
x 120
s 115
x 120
x 120
f 102
f 102
x 120
x 120
b 98
f 102
x 120
b 98
b 98
b 98
f 102
x 120
f 102
x 120
f 102
x 120
x 120
b 98
x 120
b 98
s 115
f 102
x 120
x 120
f 102
x 120
b 98
b 98
x 120
x 120
x 120
s 115
x 120
x 120
b 98
x 120
b 98
b 98
b 98
b 98
x 120
f 102
x 120
f 102
b 98
b 98
x 120
b 98
x 120
b 98
x 120
b 98
f 102
b 98
b 98
b 98
x 120
b 98
x 120
s 115
f 102
x 120
f 102
x 120
b 98
f 102
b 98
x 120
x 120
x 120
b 98
f 102
x 120
f 102
b 98
x 120
x 120
f 102
x 120
b 98
x 120
x 120
f 102
x 120
b 98
b 98
b 98
b 98
x 120
b 98
x 120
x 120
f 102
b 98
x 120
x 120
x 120
s 115
x 120
x 120
x 120
f 102
x 120
b 98
x 120
x 120
x 120
b 98
x 120
x 120
x 120
f 102
b 98
x 120
x 120
b 98
x 120
f 102
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
s 115
b 98
b 98
b 98
f 102
x 120
b 98
b 98
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
b 98
f 102
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
b 98
s 115
x 120
b 98
f 102
b 98
b 98
x 120
f 102
x 120
b 98
x 120
b 98
x 120
b 98
x 120
x 120
f 102
x 120
x 120
b 98
x 120
b 98
x 120
x 120
b 98
x 120
f 102
x 120
x 120
x 120
x 120
x 120
b 98
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
b 98
x 120
b 98
x 120
x 120
b 98
b 98
x 120
b 98
b 98
b 98
x 120
x 120
x 120
b 98
x 120
x 120
x 120
b 98
x 120
f 102
b 98
x 120
x 120
x 120
f 102
x 120
f 102
f 102
b 98
b 98
x 120
s 115
f 102
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
b 98
x 120
x 120
f 102
x 120
s 115
x 120
b 98
s 115
b 98
x 120
b 98
x 120
x 120
x 120
b 98
x 120
x 120
x 120
x 120
b 98
x 120
b 98
x 120
b 98
x 120
f 102
x 120
x 120
x 120
x 120
x 120
b 98
b 98
x 120
b 98
x 120
x 120
b 98
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
b 98
x 120
x 120
x 120
f 102
x 120
b 98
x 120
f 102
x 120
x 120
f 102
b 98
x 120
f 102
x 120
x 120
b 98
b 98
f 102
b 98
x 120
x 120
b 98
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
b 98
x 120
x 120
b 98
b 98
x 120
b 98
x 120
b 98
b 98
f 102
f 102
x 120
f 102
b 98
x 120
x 120
f 102
x 120
x 120
b 98
f 102
x 120
x 120
f 102
s 115
f 102
f 102
x 120
b 98
x 120
b 98
b 98
b 98
f 102
f 102
f 102
f 102
x 120
s 115
x 120
x 120
f 102
f 102
x 120
f 102
x 120
b 98
f 102
f 102
x 120
b 98
x 120
b 98
x 120
b 98
b 98
x 120
x 120
f 102
x 120
f 102
f 102
b 98
x 120
s 115
x 120
x 120
x 120
b 98
x 120
x 120
x 120
b 98
f 102
x 120
f 102
b 98
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
b 98
s 115
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
b 98
f 102
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
b 98
x 120
x 120
x 120
b 98
x 120
x 120
f 102
x 120
b 98
x 120
f 102
x 120
b 98
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
s 115
f 102
s 115
x 120
x 120
x 120
x 120
x 120
x 120
x 120
b 98
b 98
x 120
x 120
x 120
x 120
f 102
f 102
b 98
b 98
x 120
f 102
x 120
f 102
f 102
x 120
f 102
x 120
x 120
b 98
f 102
b 98
b 98
s 115
f 102
b 98
x 120
f 102
f 102
x 120
f 102
s 115
b 98
b 98
f 102
b 98
x 120
x 120
x 120
b 98
f 102
x 120
x 120
x 120
b 98
x 120
f 102
f 102
f 102
x 120
b 98
b 98
x 120
f 102
x 120
b 98
f 102
x 120
x 120
x 120
f 102
b 98
x 120
f 102
b 98
x 120
x 120
x 120
b 98
b 98
f 102
x 120
f 102
x 120
x 120
f 102
f 102
x 120
f 102
f 102
f 102
x 120
x 120
b 98
x 120
x 120
x 120
b 98
x 120
x 120
f 102
b 98
x 120
x 120
b 98
b 98
x 120
f 102
x 120
b 98
b 98
x 120
x 120
f 102
x 120
f 102
x 120
b 98
f 102
f 102
b 98
s 115
x 120
b 98
f 102
f 102
x 120
b 98
b 98
b 98
b 98
x 120
x 120
s 115
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
b 98
x 120
f 102
x 120
x 120
x 120
x 120
b 98
x 120
x 120
x 120
x 120
x 120
b 98
x 120
b 98
f 102
x 120
b 98
b 98
x 120
f 102
x 120
b 98
f 102
b 98
b 98
b 98
f 102
x 120
b 98
x 120
b 98
f 102
x 120
x 120
x 120
f 102
x 120
f 102
b 98
b 98
x 120
b 98
x 120
x 120
f 102
x 120
x 120
x 120
x 120
b 98
x 120
s 115
b 98
x 120
x 120
x 120
x 120
x 120
x 120
x 120
b 98
f 102
x 120
x 120
x 120
x 120
b 98
x 120
x 120
x 120
b 98
x 120
x 120
b 98
b 98
f 102
b 98
x 120
b 98
x 120
b 98
b 98
x 120
x 120
x 120
x 120
x 120
x 120
x 120
b 98
b 98
x 120
b 98
x 120
x 120
x 120
f 102
f 102
x 120
f 102
s 115
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
b 98
s 115
x 120
x 120
x 120
b 98
b 98
x 120
b 98
f 102
s 115
x 120
s 115
f 102
f 102
b 98
b 98
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
b 98
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
b 98
x 120
x 120
b 98
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
b 98
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
b 98
x 120
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
x 120
b 98
x 120
x 120
x 120
f 102
f 102
f 102
b 98
f 102
f 102
x 120
b 98
f 102
x 120
f 102
b 98
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
b 98
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
b 98
f 102
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
f 102
f 102
f 102
x 120
f 102
x 120
f 102
b 98
b 98
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
b 98
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
b 98
f 102
b 98
f 102
b 98
x 120
f 102
x 120
s 115
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
f 102
b 98
x 120
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
b 98
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
b 98
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
b 98
x 120
f 102
f 102
f 102
b 98
x 120
x 120
x 120
x 120
b 98
x 120
x 120
f 102
b 98
x 120
x 120
f 102
x 120
x 120
x 120
b 98
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
b 98
x 120
x 120
b 98
x 120
b 98
x 120
x 120
b 98
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
f 102
f 102
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
f 102
x 120
f 102
f 102
x 120
x 120
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
f 102
b 98
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
b 98
f 102
f 102
x 120
b 98
x 120
f 102
x 120
f 102
f 102
x 120
f 102
b 98
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
x 120
f 102
x 120
f 102
f 102
x 120
x 120
b 98
x 120
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
b 98
f 102
f 102
x 120
x 120
x 120
f 102
f 102
f 102
f 102
x 120
f 102
x 120
f 102
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
f 102
b 98
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
f 102
f 102
b 98
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
b 98
f 102
f 102
f 102
f 102
x 120
b 98
f 102
f 102
x 120
f 102
x 120
x 120
b 98
x 120
f 102
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
f 102
x 120
b 98
x 120
x 120
f 102
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
f 102
x 120
x 120
b 98
f 102
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
f 102
b 98
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
f 102
f 102
f

 102
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
b 98
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
b 98
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
x 120
x 120
b 98
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
x 120
f 102
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
f 102
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
x 120
f 102
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
f 102
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
x 120
f 102
x 120
f 102
f 102
f 102
x 120
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
f 102
f 102
x 120
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
x 120
f 102
f 102
x 120
f 102
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
f 102
x 120
f 102
x 120
f 102
f 102
f 102
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
f 102
x 120
f 102
f 102
f 102
x 120
f 102
x 120
f 102
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
f 102
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
x 120
f 102
f 102
x 120
f 102
f 102
x 120
x 120
f 102
f 102
x 120
x 120
f 102
f 102
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
f 102
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
x 120
f 102
f 102
x 120
f 102
f 102
x 120
x 120
x 120
f 102
f 102
f 102
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
f 102
f 102
x 120
f 102
x 120
f 102
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
f 102
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
x 120
f 102
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
x 120
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
f 102
f 102
x 120
f 102
x 120
f 102
f 102
f 102
x 120
f 102
f 102
f 102
x 120
x 120
f 102
f 102
f 102
f 102
f 102
x 120
x 120
x 120
f 102
f 102
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
f 102
x 120
f 102
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
f 102
x 120
f 102
x 120
f 102
f 102
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
f 102
f 102
x 120
f 102
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
f 102
f 102
f 102
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
f 102
x 120
f 102
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
f 102
f 102
f 102
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
b 98
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
k 107
f 102
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
f 102
f 102
k 107
x 120
f 102
f 102
f 102
x 120
f 102
x 120
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
k 107
f 102
x 120
x 120
f 102
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
b 98
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
f 102
f 102
x 120
f 102
f 102
x 120
x 120
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
f 102
f 102
f 102
x 120
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
f 102
x 120
k 107
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
f 102
x 120
x 120
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
f 102
f 102
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
f 102
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
f 102
x 120
x 120
f 102
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
f 102
f 102
x 120
x 120
f 102
f 102
x 120
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
f 102
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
f 102
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
f 102
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
f 102
f 102
x 120
f 102
x 120
f 102
f 102
f 102
k 107
f 102
f 102
x 120
f 102
f 102
f 102
f 102
x 120
x 120
x 120
f 102
b 98
f 102
x 120
f 102
f 102
k 107
f 102
f 102
k 107
x 120
x 120
x 120
x 120
f 102
b 98
x 120
f 102
b 98
f 102
x 120
k 107
x 120
f 102
f 102
x 120
x 120
x 120
x 120
x 120
x 120
x 120
f 102
k 107
f 102
f 102
x 120
f 102
f 102
f 102
x 120
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
f 102
x 120
b 98
f 102
x 120
f 102
x 120
f 102
f 102
x 120
f 102
x 120
x 120
f 102
x 120
x 120
f 102
f 102
x 120
f 102
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
f 102
f 102
x 120
x 120
x 120
f 102
f 102
x 120
f 102
f 102
x 120
x 120
k 107
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
x 120
k 107
f 102
x 120
f 102
x 120
f 102
k 107
f 102
x 120
x 120
x 120
f 102
f 102
f 102
f 102
x 120
f 102
f 102
f 102
x 120
f 102
x 120
f 102
f 102
f 102
f 102
x 120
k 107
f 102
f 102
x 120
f 102
f 102
x 120
f 102
f 102
f 102
f 102
f 102
x 120
x 120
f 102
f 102
x 120
x 120
f 102
f 102
x 120
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
f 102
x 120
b 98
f 102
f 102
f 102
x 120
f 102
f 102
x 120
x 120
f 102
x 120
x 120
f 102
k 107
f 102
x 120
x 120
f 102
f 102
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
x 120
x 120
x 120
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
f 102
f 102
f 102
x 120
f 102
x 120
x 120
x 120
k 107
f 102
x 120
f 102
x 120
f 102
x 120
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
f 102
x 120
f 102
x 120
x 120
x 120
f 102
x 120
x 120
f 102
f 102
f 102
f 102
x 120
f 102
f 102
x 120
x 120
k 107
f 102
k 107
f 102
f 102
x 120
x 120
f 102
f 102
x 120
f 102
x 120
b 98
k 107
x 120
x 120
k 107
f 102
x 120
x 120
x 120
x 120
f 102
x 120
f 102
x 120
f 102
f 102
f 102
x 120
x 120
x 120
k 107
x 120
x 120
f 102
f 102
k 107
x 120
f 102
f 102
c 99
x 120
b 98
x 120
f 102
b 98
x 120
x 120

----

In [44]:
target = []
data = []

for row_index, row in mr.iterrows():
   print(row_index, ":", row)

0 : 0     p
1     x
2     s
3     n
4     t
5     p
6     f
7     c
8     n
9     k
10    e
11    e
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    k
21    s
22    u
Name: 0, dtype: str
1 : 0     e
1     x
2     s
3     y
4     t
5     a
6     f
7     c
8     b
9     k
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    n
22    g
Name: 1, dtype: str
2 :

0     e
1     b
2     s
3     w
4     t
5     l
6     f
7     c
8     b
9     n
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    n
22    m
Name: 2, dtype: str
3 : 0     p
1     x
2     y
3     w
4     t
5     p
6     f
7     c
8     n
9     n
10    e
11    e
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    k
21    s
22    u
Name: 3, dtype: str
4 : 0     e
1     x
2     s
3     g
4     f
5     n
6     f
7     w
8     b
9     k
10    t
11    e
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    e
20    n
21    a
22    g
Name: 4, dtype: str
5 : 0     e
1     x
2     y
3     y
4     t
5     a
6     f
7     c
8     b
9     n
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    k
21    n
22    g
Name: 5, dtype: str
6 : 0     e
1     b
2     s
3     w
4     t
5     a
6     f
7     c
8     b
9     g
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    k
21    n
22    m
Name: 6, dtype: str
7 : 0     e
1     b
2     y
3     w
4     t
5     l
6     f
7     c
8     b
9     n
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    s
22    m
Name: 7, dtype: str
8 : 0     p
1     x
2     y
3     w
4     t
5     p
6     f
7     c
8     n
9     p
10    e
11    e
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    k
21    v
22    g
Name: 8, dtype: str
9 : 0     e
1     b
2     s
3     y
4     t
5     a
6     f
7     c
8     b
9     g
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    k
21    s
22    m
Name: 9, dtype: str
10 : 0     e
1     x
2     y
3     y
4     t
5     l
6     f
7     c
8     b
9     g
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    n
22    g
Name: 10, dtype: str
11 : 0     e
1     x
2     y
3     y
4     t
5     a
6     f
7     c
8     b
9     n
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    k
21    s
22    m
Name: 11, dtype: str
12 : 0     e
1     b
2     s
3     y
4     t
5     a
6     f
7     c
8     b
9     w
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    s
22    g
Name: 12, dtype: str
13 : 0     p
1     x
2     y
3     w
4     t
5     p
6     f
7     c
8     n
9     k
10    e
11    e
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    v
22    u
Name: 13, dtype: str
14 : 0     e
1     x
2     f
3     n
4     f
5     n
6     f
7     w
8     b
9     n
10    t
11    e
12    s
13    f
14    w
15    w
16    p
17    w
18    o
19    e
20    k
21    a
22    g
Name: 14, dtype: str
15 : 0     e
1     s
2     f
3     g
4     f
5     n
6     f
7     c
8     n
9     k
10    e
11    e
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    y
22    u
Name: 15, dtype: str
16 : 0     e
1     f
2     f
3     w
4     f
5     n
6     f
7     w
8     b
9     k
10    t
11    e
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    e
20    n
21    a
22    g
Name: 16, dtype: str
17 : 0     p
1     x
2     s
3     n
4     t
5     p
6     f
7     c
8     n
9     n
10    e
11    e
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    k
21    s
22    g
Name: 17, dtype: str
18 : 0     p
1     x
2     y
3     w
4     t
5     p
6     f
7     c
8     n
9     n
10    e
11    e
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    s
22    u
Name: 18, dtype: str
19 : 0     p
1     x
2     s
3     n
4     t
5     p
6     f
7     c
8     n
9     k
10    e
11    e
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    s
22    u
Name: 19, dtype: str
20 : 0     e
1     b
2     s
3     y
4     t
5     a
6     f
7     c
8     b
9     k
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    s
22    m
Name: 20, dtype: str
21 : 0     p
1     x
2     y
3     n
4     t
5     p
6     f
7     c
8     n
9     n
10    e
11    e
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    v
22    g
Name: 21, dtype: str
22 : 0     e
1     b
2     y
3     y
4     t
5     l
6     f
7     c
8     b
9     k
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    s
22    m
Name: 22, dtype: str
23 : 0     e
1     b
2     y
3     w
4     t
5     a
6     f
7     c
8     b
9     w
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    n
22    m
Name: 23, dtype: str
24 : 0     e
1     b
2     s
3     w
4     t
5     l
6     f
7     c
8     b
9     g
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    k
21    s
22    m
Name: 24, dtype: str
25 : 0     p
1     f
2     s
3     w
4     t
5     p
6     f
7     c
8     n
9     n
10    e
11    e
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    v
22    g
Name: 25, dtype: str
26 : 0     e
1     x
2     y
3     y
4     t
5     a
6     f
7     c
8     b
9     n
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    n
22    m
Name: 26, dtype: str
27 : 0     e
1     x
2     y
3     w
4     t
5     l
6     f
7     c
8     b
9     w
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    n
22    m
Name: 27, dtype: str
28 : 0     e
1     f
2     f
3     n
4     f
5     n
6     f
7     c
8     n
9     k
10    e
11    e
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    k
21    y
22    u
Name: 28, dtype: str
29 : 0     e
1     x
2     s
3     y
4     t
5     a
6     f
7     w
8     n
9     n
10    t
11    b
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    v
22    d
Name: 29, dtype: str
30 : 0     e
1     b
2     s
3     y
4     t
5     l
6     f
7     c
8     b
9     g
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    n
22    m
Name: 30, dtype: str
31 : 0     p
1     x
2     y
3     w
4     t
5     p
6     f
7     c
8     n
9     k
10    e
11    e
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    s
22    u
Name: 31, dtype: str
32 : 0     e
1     x
2     y
3     y
4     t
5     l
6     f
7     c
8     b
9     n
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    n
22    m
Name: 32, dtype: str
33 : 0     e
1     x
2     y
3     n
4     t
5     l
6     f
7     c
8     b
9     p
10    e
11    r
12    s
13    y
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    y
22    p
Name: 33, dtype: str
34 : 0     e
1     b
2     y
3     y
4     t
5     l
6     f
7     c
8     b
9     n
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    s
22    m
Name: 34, dtype: str
35 : 0     e
1     x
2     f
3     y
4     t
5     l
6     f
7     w
8     n
9     w
10    t
11    b
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    v
22    d
Name: 35, dtype: str
36 : 0     e
1     s
2     f
3     g
4     f
5     n
6     f
7     c
8     n
9     k
10    e
11    e
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    k
21    v
22    u
Name: 36, dtype: str
37 : 0     p
1     x
2     y
3     n
4     t
5     p
6     f
7     c
8     n
9     w
10    e
11    e
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    s
22    u
Name: 37, dtype: str
38 : 0     e
1     x
2     f
3     y
4     t
5     a
6     f
7     w
8     n
9     p
10    t
11    b
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    v
22    d
Name: 38, dtype: str
39 : 0     e
1     b
2     s
3     y
4     t
5     l
6     f
7     c
8     b
9     k
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    k
21    s
22    m
Name: 39, dtype: str
40 : 0     e
1     b
2     y
3     y
4     t
5     a
6     f
7     c
8     b
9     n
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    s
22    g
Name: 40, dtype: str
41 : 0     e
1     x
2     y
3     y
4     t
5     l
6     f
7     c
8     b
9     n
10    e
11    r
12    s
13    y
14    w
15    w
16    p
17    w
18    o
19    p
20    k
21    y
22    p
Name: 41, dtype: str
42 : 0     e
1     x
2     f
3     n
4     f
5     n
6     f
7     c
8     n
9     g
10    e
11    e
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    k
21    y
22    u
Name: 42, dtype: str
43 : 0     p
1     x
2     y
3     w
4     t
5     p
6     f
7     c
8     n
9     p
10    e
11    e
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    v
22    g
Name: 43, dtype: str
44 : 0     e
1     x
2     s
3     y
4     t
5     a
6     f
7     c
8     b
9     w
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    k
21    n
22    m
Name: 44, dtype: str
45 : 0     e
1     x
2     y
3     w
4     t
5     a
6     f
7     c
8     b
9     n
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    n
22    g
Name: 45, dtype: str
46 : 0     e
1     x
2     y
3     y
4     t
5     l
6     f
7     c
8     b
9     k
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    k
21    s
22    m
Name: 46, dtype: str
47 : 0     e
1     x
2     s
3     w
4     t
5     l
6     f
7     c
8     b
9     w
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    n
22    m
Name: 47, dtype: str
48 : 0     e
1     x
2     y
3     y
4     t
5     l
6     f
7     c
8     b
9     n
10    e
11    r
12    s
13    y
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    s
22    p
Name: 48, dtype: str
49 : 0     e
1     f
2     y
3     y
4     t
5     l
6     f
7     c
8     b
9     w
10    e
11    r
12    s
13    y
14    w
15    w
16    p
17    w
18    o
19    p
20    k
21    s
22    p
Name: 49, dtype: str
50 : 0     e
1     x
2     y
3     n
4     t
5     a
6     f
7     c
8     b
9     w
10    e
11    r
12    s
13    y
14    w
15    w
16    p
17    w
18    o
19    p
20    k
21    s
22    g
Name: 50, dtype: str
51 : 0     e
1     x
2     s
3     w
4     t
5     l
6     f
7     c
8     b
9     k
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    k
21    s
22    g
Name: 51, dtype: str
52 : 0     e
1     b
2     s
3     w
4     t
5     l
6     f
7     c
8     b
9     k
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    n
22    m
Name: 52, dtype: str
53 : 0     p
1     x
2     y
3     n
4     t
5     p
6     f
7     c
8     n
9     k
10    e
11    e
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    v
22    u
Name: 53, dtype: str
54 : 0     p
1     x
2     s
3     w
4     t
5     p
6     f
7     c
8     n
9     k
10    e
11    e
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    k
21    v
22    u
Name: 54, dtype: str
55 : 0     e
1     b
2     y
3     y
4     t
5     a
6     f
7     c
8     b
9     w
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    k
21    s
22    m
Name: 55, dtype: str
56 : 0     e
1     f
2     f
3     g
4     f
5     n
6     f
7     w
8     b
9     n
10    t
11    e
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    e
20    n
21    a
22    g
Name: 56, dtype: str
57 : 0     e
1     b
2     s
3     w
4     t
5     a
6     f
7     c
8     b
9     w
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    n
22    g
Name: 57, dtype: str
58 : 0     e
1     x
2     s
3     y
4     t
5     l
6     f
7     c
8     b
9     k
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    k
21    n
22    g
Name: 58, dtype: str
59 : 0     e
1     x
2     y
3     n
4     t
5     a
6     f
7     c
8     b
9     p
10    e
11    r
12    s
13    y
14    w
15    w
16    p
17    w
18    o
19    p
20    k
21    y
22    p
Name: 59, dtype: str
60 : 0     e
1     s
2     f
3     g
4     f
5     n
6     f
7     c
8     n
9     k
10    e
11    e
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    v
22    u
Name: 60, dtype: str
61 : 0     e
1     b
2     y
3     y
4     t
5     a
6     f
7     c
8     b
9     k
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    s
22    m
Name: 61, dtype: str
62 : 0     e
1     b
2     s
3     y
4     t
5     l
6     f
7     c
8     b
9     g
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    s
22    m
Name: 62, dtype: str
63 : 0     e
1     b
2     y
3     y
4     t
5     l
6     f
7     c
8     b
9     g
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    n
22    m
Name: 63, dtype: str
64 : 0     e
1     b
2     y
3     w
4     t
5     l
6     f
7     c
8     b
9     n
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    s
22    g
Name: 64, dtype: str
65 : 0     e
1     f
2     s
3     n
4     f
5     n
6     f
7     w
8     b
9     k
10    t
11    e
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    e
20    k
21    a
22    g
Name: 65, dtype: str
66 : 0     e
1     x
2     s
3     w
4     t
5     l
6     f
7     c
8     b
9     n
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    k
21    s
22    g
Name: 66, dtype: str
67 : 0     e
1     f
2     y
3     y
4     t
5     a
6     f
7     c
8     b
9     w
10    e
11    r
12    s
13    y
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    s
22    g
Name: 67, dtype: str
68 : 0     e
1     x
2     y
3     y
4     t
5     a
6     f
7     c
8     b
9     w
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    k
21    n
22    g
Name: 68, dtype: str
69 : 0     e
1     x
2     f
3     g
4     f
5     n
6     f
7     c
8     n
9     p
10    e
11    e
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    v
22    u
Name: 69, dtype: str
70 : 0     e
1     f
2     f
3     y
4     t
5     l
6     f
7     w
8     n
9     p
10    t
11    b
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    v
22    d
Name: 70, dtype: str
71 : 0     e
1     b
2     y
3     w
4     t
5     l
6     f
7     c
8     b
9     g
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    s
22    m
Name: 71, dtype: str
72 : 0     e
1     f
2     f
3     y
4     t
5     l
6     f
7     w
8     n
9     w
10    t
11    b
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    v
22    d
Name: 72, dtype: str
73 : 0     e
1     x
2     y
3     n
4     t
5     a
6     f
7     c
8     b
9     p
10    e
11    r
12    s
13    y
14    w
15    w
16    p
17    w
18    o
19    p
20    k
21    s
22    p
Name: 73, dtype: str
74 : 0     e
1     b
2     s
3     y
4     t
5     a
6     f
7     c
8     b
9     k
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    k
21    s
22    g
Name: 74, dtype: str
75 : 0     e
1     f
2     s
3     y
4     t
5     l
6     f
7     w
8     n
9     p
10    t
11    b
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    v
22    d
Name: 75, dtype: str
76 : 0     e
1     x
2     s
3     w
4     t
5     l
6     f
7     w
8     n
9     n
10    t
11    b
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    u
21    v
22    d
Name: 76, dtype: str
77 : 0     e
1     f
2     y
3     n
4     t
5     l
6     f
7     c
8     b
9     p
10    e
11    r
12    s
13    y
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    y
22    p
Name: 77, dtype: str
78 : 0     p
1     x
2     y
3     n
4     t
5     p
6     f
7     c
8     n
9     w
10    e
11    e
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    v
22    u
Name: 78, dtype: str
79 : 0     e
1     f
2     y
3     n
4     t
5     a
6     f
7     c
8     b
9     n
10    e
11    r
12    s
13    y
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    y
22    g
Name: 79, dtype: str
80 : 0     e
1     x
2     s
3     n
4     f
5     n
6     f
7     w
8     b
9     k
10    t
11    e
12    f
13    s
14    w
15    w
16    p
17    w
18    o
19    e
20    n
21    s
22    g
Name: 80, dtype: str
81 : 0     p
1     x
2     y
3     w
4     t
5     p
6     f
7     c
8     n
9     w
10    e
11    e
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    k
21    s
22    g
Name: 81, dtype: str
82 : 0     e
1     f
2     f
3     g
4     f
5     n
6     f
7     c
8     n
9     n
10    e
11    e
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    y
22    u
Name: 82, dtype: str
83 : 0     e
1     x
2     f
3     g
4     f
5     n
6     f
7     w
8     b
9     n
10    t
11    e
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    e
20    n
21    s
22    g
Name: 83, dtype: str
84 : 0     e
1     x
2     y
3     y
4     t
5     l
6     f
7     c
8     b
9     w
10    e
11    r
12    s
13    y
14    w
15    w
16    p
17    w
18    o
19    p
20    k
21    s
22    g
Name: 84, dtype: str
85 : 0     e
1     x
2     s
3     n
4     f
5     n
6     f
7     w
8     b
9     k
10    t
11    e
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    e
20    k
21    s
22    g
Name: 85, dtype: str
86 : 0     e
1     b
2     s
3     w
4     t
5     a
6     f
7     c
8     b
9     w
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    k
21    s
22    g
Name: 86, dtype: str
87 : 0     e
1     x
2     s
3     w
4     t
5     l
6     f
7     c
8     b
9     n
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    s
22    g
Name: 87, dtype: str
88 : 0     e
1     f
2     y
3     n
4     t
5     l
6     f
7     c
8     b
9     w
10    e
11    r
12    s
13    y
14    w
15    w
16    p
17    w
18    o
19    p
20    k
21    y
22    g
Name: 88, dtype: str
89 : 0     e
1     s
2     f
3     n
4     f
5     n
6     f
7     c
8     n
9     n
10    e
11    e
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    v
22    u
Name: 89, dtype: str
90 : 0     e
1     x
2     f
3     n
4     f
5     n
6     f
7     c
8     n
9     n
10    e
11    e
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    y
22    u
Name: 90, dtype: str
91 : 0     e
1     b
2     s
3     w
4     t
5     l
6     f
7     c
8     b
9     k
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    k
21    s
22    g
Name: 91, dtype: str
92 : 0     e
1     x
2     y
3     y
4     t
5     a
6     f
7     c
8     b
9     g
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    k
21    s
22    g
Name: 92, dtype: str
93 : 0     e
1     x
2     y
3     y
4     t
5     l
6     f
7     c
8     b
9     g
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    k
21    n
22    m
Name: 93, dtype: str
94 : 0     e
1     x
2     s
3     n
4     f
5     n
6     f
7     w
8     b
9     n
10    t
11    e
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    e
20    n
21    a
22    g
Name: 94, dtype: str
95 : 0     e
1     x
2     s
3     w
4     t
5     a
6     f
7     c
8     b
9     g
10    e
11    c
12    s
13    s
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    s
22    g
Name: 95, dtype: str
96 : 0     e
1     f
2     y
3     n
4     t
5     l
6     f
7     c
8     b
9     p
10    e
11    r
12    s
13    y
14    w
15    w
16    p
17    w
18    o
19    p
20    n
21    s
22    g
Name: 96, dtype: str
97 : 0     e
1     x
2     s
3     y
4     t
5     a
6     f
7     c